[package]
name = "shell-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
dirs-next.workspace = true
keyring.workspace = true
serde.workspace = true
serde_json.workspace = true
shell-core = { path = "../core" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_System_Memory"] }
