[package]
name = "shell-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serialport.workspace = true
shell-core = { path = "../core" }
shell-platform = { path = "../platform" }
ssh2.workspace = true
tracing.workspace = true
